name: URL Shortener CI/CD

on:
  push:
    branches:
      - "*"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go:
          - 1.19

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go version
      - run: go mod download
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run: staticcheck ./...
      - run: go test -v ./test/unit/...
      - run: GOOS=linux GOARCH=amd64 go build -o build/main ./cmd/lambda/main.go
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9
      - run: terraform fmt -check
        working-directory: ./terraform
      - run: terraform init
        working-directory: ./terraform
      - run: terraform validate -no-color
        working-directory: ./terraform
      - run: terraform plan -no-color -input=false
        working-directory: ./terraform
      - run: tar cf ./package.tar ./build ./terraform
      - name: Upload
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/master'
        with:
          name: package
          path: ./package.tar

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: package
      - run: tar -xf ./package.tar
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform
      - uses: geekyeggo/delete-artifact@v2
        with:
            name: package
        if: always()